name = "draigercms.github.io"
license = "MIT"
licenselink = "https://github.com/draigercms/draigercms.github.io/blob/main/LICENSE"
description = "Security Administrator of JK-acme Foundation."

homepage = "https://github.com/draigercms/draigercms.github.io"
netlify_site = "https://draigercms.netlify.app"

# tags = ["landing", "docs", "blog", "responsive", "minimal", "light", "dark", "multilingual", "dark mode", "tailwind", "company", "gallery"]
# features = ["secure", "fast", "search", "dark mode", "widgets"]

# [author]
#   name = "Drai Tixian"
#   homepage = "https://draigercms.bearblog.dev/"
